services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/potluck
  #     - RUST_LOG=info
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./:/app

  db:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=potluck
    volumes:
      - ./.dockerdata:/var/lib/postgresql/data
